name: ever_app
description: Ever的家园 - Libi与Ever的聊天App
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.0
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true